name: deploy-staging

on:
  schedule:
    - cron: '42 */12 * * *'
  push:
    branches: [ staging ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/deploy-staging.yaml'
  repository_dispatch:
    types: [ deploy_staging ]
  workflow_dispatch:

jobs:
  build:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry-staging'
    name: Build site
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://geodetic-staging.isotc211.org
    steps:
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npx @paneron/site-builder@0.0.41 --outdir dist --datadir gr-registry
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
