name: deploy-proposals

on:
  schedule:
    - cron: '48 */12 * * *'
  push:
    branches: [ master ]
    paths-ignore:
      - '/docs/**'
      - '.github/workflows/*'
      - '!.github/workflows/deploy-proposals.yaml'
  repository_dispatch:
    types: [ deploy-proposals ]
  workflow_dispatch:

jobs:
  deploy-proposals:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry'
    name: Force proposals instance to deploy
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_REGISTRY_REPOSITORY_DISPATCH_JEFFREYLAU }}
          repository: isogr/registry-proposals
          event-type: deploy-proposals
