name: mirror-staging

on:
  push:
    branches: [ staging ]
  repository_dispatch:
    types: [ mirror_staging ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: n14s/github-mirror-action@v1
        with:
          origin: registry-staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
