name: propagate-master-to-staging

on:
  repository_dispatch:
    types: [ propagate-master-to-staging ]
  workflow_dispatch:

jobs:
  update:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry'
    name: Propagate changes from master to staging
    runs-on: ubuntu-latest
    steps:
      # Fetch only the production branch
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: staging
          # Default fetch-depth is 1.
          # Need all history to be able to push to Production.
          fetch-depth: 0
      - name: Force push to staging branch
        shell: bash
        run: |
          git reset --hard origin/master
          git push -f

  force-propagate:
    name: Force propagate changes to staging instance
    needs: [update]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: reset-staging
