name: propagate-proposals-to-master

on:
  # Manual operation only.
  # TODO: Add on-push, but detect if there are changes to proposals/
  repository_dispatch:
    types: [ propagate-proposals-to-master ]
  workflow_dispatch:

jobs:
  update:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry-proposals'
    name: Propagate changes from proposals to master
    runs-on: ubuntu-latest
    steps:
      # Fetch only the production branch
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: master
          # Default fetch-depth is 1.
          # Need all history to be able to push to Production.
          fetch-depth: 0
      - name: Push to master branch
        shell: bash
        run: |
          git reset --hard origin/proposals
          git push
