name: propagate-proposals-to-master

on:
  push:
    branches:
      - proposals
  repository_dispatch:
    types: [ propagate-proposals-to-master ]
  workflow_dispatch:

jobs:
  # Run this if on push
  detect-changes-in-proposals:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry-proposals'
    name: Detect changes in proposals/ folder in branch 'proposals'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: proposals
          fetch-depth: 0
      - name: Detect status changes to 'accepted' in proposals
        id: output
        shell: bash
        run: |
          case ${{ github.event_name }} in
            push)
              # Just need to check the last two commits?
              # Ideally, check against master branch:
              if git diff origin/master HEAD gr-registry/proposals/*/main.yaml | grep -q '^+state: accepted'
              then
                echo "needs-updating=true" >> $GITHUB_OUTPUT
              else
                echo "needs-updating=false" >> $GITHUB_OUTPUT
              fi
            ;;
            repository_dispatch)
              echo "needs-updating=true" >> $GITHUB_OUTPUT
            ;;
            workflow_dispatch)
              echo "needs-updating=true" >> $GITHUB_OUTPUT
            ;;
            *)
              echo "::set-output name=needs-updating::false"
            ;;
          esac

  update:
    name: Propagate changes from proposals to master
    needs: [detect-changes-in-proposals]
    # Run if manual/repository dispatch or if any YAML files in proposals/
    # folder have updated key 'status' to 'accepted'.
    if: ${{ needs.detect-changes-in-proposals.outputs.needs-updating == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Fetch only the production branch
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: master
          # Default fetch-depth is 1.
          # Need all history to be able to push to Production.
          fetch-depth: 0
      # - name: Determine if there are changes between the two branches
      #   id: output
      #   shell: bash
      #   run: |
      #     if (( $(git diff origin/proposals HEAD | wc -l) > 0 ))
      #     then
      #       echo "needs-updating=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "needs-updating=false" >> $GITHUB_OUTPUT
      #     fi
      - name: Push to master branch
        shell: bash
        run: |
          git reset --hard origin/proposals
          git push

  force-propagate:
    name: Force propagate changes to master
    needs: [detect-changes-in-proposals, update]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        # if: ${{ needs.detect-changes-in-proposals.outputs.needs-updating == 'true' }}
        # if: ${{ needs.update.outputs.needs-updating == 'true' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: mirror-production
