name: reset-staging

on:
  repository_dispatch:
    types: [ reset-staging ]
  workflow_dispatch:

jobs:
  reset:
    # The same repo is mirrored to different GitHub repos.
    if: github.repository == 'isogr/registry'
    name: Reset repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: master
          # Default fetch-depth is 1.
          # Need all history to be able to push to mirror.
          fetch-depth: 0
          token: ${{ secrets.GH_OR_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Push to mirror
        shell: bash
        run: |
          # Add the mirror as a new remote
          git remote add mirror https://github.com/isogr/registry-staging.git
          # Push branch
          git push -f mirror master:staging
  force-deploy:
    name: Force staging to deploy
    needs: [reset]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_REGISTRY_REPOSITORY_DISPATCH_JEFFREYLAU }}
          repository: isogr/registry-staging
          event-type: deploy-staging
